### ISSUE TITLE
Error starting in FlameCord 1.19

### ISSUE THREAD

**Issue by NishiVT** [dejvokep/safe-net#15]
[23:00:10 WARN]: Exception encountered when loading plugin: SafeNET
java.lang.NumberFormatException: For input string: "1.0.3"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:786) ~[?:?]
        at dev.dejvokep.safenet.bungeecord.SafeNetBungeeCord.onEnable(SafeNetBungeeCord.java:63) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:356) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:d1fe574:unknown]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:320) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:d1fe574:unknown]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:54) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:d1fe574:unknown]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:d1fe574:unknown]

**Comment by TheWylot** [comment]
same error
